/** Generated by YAKINDU Statechart Tools code generator. */


#include "sc_types.h"

#include "Statechart.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_main_region_Not_Counting_default(Statechart* handle);
static void enseq_main_region_Counting_default(Statechart* handle);
static void enseq_main_region_Counting_S1_C0_default(Statechart* handle);
static void enseq_main_region_Counting_S1_C1_default(Statechart* handle);
static void enseq_main_region_Counting_S2_B0_default(Statechart* handle);
static void enseq_main_region_Counting_S2_B1_default(Statechart* handle);
static void enseq_main_region_Counting_S3_A0_default(Statechart* handle);
static void enseq_main_region_Counting_S3_A1_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void enseq_main_region_Counting_S1_default(Statechart* handle);
static void enseq_main_region_Counting_S2_default(Statechart* handle);
static void enseq_main_region_Counting_S3_default(Statechart* handle);
static void exseq_main_region_Not_Counting(Statechart* handle);
static void exseq_main_region_Counting(Statechart* handle);
static void exseq_main_region_Counting_S1_C0(Statechart* handle);
static void exseq_main_region_Counting_S1_C1(Statechart* handle);
static void exseq_main_region_Counting_S2_B0(Statechart* handle);
static void exseq_main_region_Counting_S2_B1(Statechart* handle);
static void exseq_main_region_Counting_S3_A0(Statechart* handle);
static void exseq_main_region_Counting_S3_A1(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void exseq_main_region_Counting_S1(Statechart* handle);
static void exseq_main_region_Counting_S2(Statechart* handle);
static void exseq_main_region_Counting_S3(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);
static void react_main_region_Counting_S1__entry_Default(Statechart* handle);
static void react_main_region_Counting_S2__entry_Default(Statechart* handle);
static void react_main_region_Counting_S3__entry_Default(Statechart* handle);

/*! State machine reactions. */
static sc_integer react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Not Counting. */
static sc_integer main_region_Not_Counting_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Counting. */
static sc_integer main_region_Counting_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state C0. */
static sc_integer main_region_Counting_S1_C0_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state C1. */
static sc_integer main_region_Counting_S1_C1_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state B0. */
static sc_integer main_region_Counting_S2_B0_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state B1. */
static sc_integer main_region_Counting_S2_B1_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state A0. */
static sc_integer main_region_Counting_S3_A0_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state A1. */
static sc_integer main_region_Counting_S3_A1_react(Statechart* handle, const sc_integer transitioned_before);


static void swap_in_events(Statechart* handle);

static void clear_in_events(Statechart* handle);

static void swap_internal_events(Statechart* handle);

static void clear_internal_events(Statechart* handle);

static void micro_step(Statechart* handle);





void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	clear_internal_events(handle);
	swap_in_events(handle);
	swap_internal_events(handle);
	
	sc_observable_init(&handle->iface.end);
	
	/* Default init sequence for statechart Statechart */
	handle->iface.Aout = bool_false;
	handle->iface.Bout = bool_false;
	handle->iface.Cout = bool_false;
	
	handle->isExecuting = bool_false;
}

void statechart_run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	swap_in_events(handle);
	do
	{ 
		micro_step(handle);
		swap_internal_events(handle);
	} while (((handle->current.internal.lt1_raised == bool_true) || (handle->current.internal.lt2_raised == bool_true)) || (handle->current.internal.local_end_raised == bool_true));
	handle->isExecuting = bool_false;
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_Not_Counting :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_NOT_COUNTING] == Statechart_main_region_Not_Counting
			);
			break;
		case Statechart_main_region_Counting :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING] >= Statechart_main_region_Counting
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING] <= Statechart_main_region_Counting_S3_A1);
			break;
		case Statechart_main_region_Counting_S1_C0 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING_S1_C0] == Statechart_main_region_Counting_S1_C0
			);
			break;
		case Statechart_main_region_Counting_S1_C1 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING_S1_C1] == Statechart_main_region_Counting_S1_C1
			);
			break;
		case Statechart_main_region_Counting_S2_B0 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING_S2_B0] == Statechart_main_region_Counting_S2_B0
			);
			break;
		case Statechart_main_region_Counting_S2_B1 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING_S2_B1] == Statechart_main_region_Counting_S2_B1
			);
			break;
		case Statechart_main_region_Counting_S3_A0 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING_S3_A0] == Statechart_main_region_Counting_S3_A0
			);
			break;
		case Statechart_main_region_Counting_S3_A1 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_COUNTING_S3_A1] == Statechart_main_region_Counting_S3_A1
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void swap_in_events(Statechart* handle)
{
	handle->current.iface.tick_raised = handle->iface.tick_raised;
	handle->iface.tick_raised = bool_false;
	handle->current.iface.init_raised = handle->iface.init_raised;
	handle->iface.init_raised = bool_false;
}

static void clear_in_events(Statechart* handle)
{
	handle->iface.tick_raised = bool_false;
	handle->iface.init_raised = bool_false;
}

static void swap_internal_events(Statechart* handle)
{
	/* When processing internal events all incoming events are processed and must be cleared from current buffer. */
	handle->current.iface.tick_raised = bool_false;
	handle->current.iface.init_raised = bool_false;
	/* Swap all internal events. */
	handle->current.internal.lt1_raised = handle->internal.lt1_raised;
	handle->internal.lt1_raised = bool_false;
	handle->current.internal.lt2_raised = handle->internal.lt2_raised;
	handle->internal.lt2_raised = bool_false;
	handle->current.internal.local_end_raised = handle->internal.local_end_raised;
	handle->internal.local_end_raised = bool_false;
}

static void clear_internal_events(Statechart* handle)
{
	handle->internal.lt1_raised = bool_false;
	handle->internal.lt2_raised = bool_false;
	handle->internal.local_end_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
 			sc_integer transitioned = -1;
	handle->stateConfVectorPosition = 0;
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Not_Counting :
		{
			transitioned = main_region_Not_Counting_react(handle, transitioned);
			break;
		}
		case Statechart_main_region_Counting_S1_C0 :
		{
			transitioned = main_region_Counting_S1_C0_react(handle, transitioned);
			break;
		}
		case Statechart_main_region_Counting_S1_C1 :
		{
			transitioned = main_region_Counting_S1_C1_react(handle, transitioned);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	if ((handle->stateConfVectorPosition) < (1))
	{ 
		switch(handle->stateConfVector[ 1 ])
		{
			case Statechart_main_region_Counting_S2_B0 :
			{
				transitioned = main_region_Counting_S2_B0_react(handle, transitioned);
				break;
			}
			case Statechart_main_region_Counting_S2_B1 :
			{
				transitioned = main_region_Counting_S2_B1_react(handle, transitioned);
				break;
			}
			default: 
				/* do nothing */
				break;
		}
	} if ((handle->stateConfVectorPosition) < (2))
	{ 
		switch(handle->stateConfVector[ 2 ])
		{
			case Statechart_main_region_Counting_S3_A0 :
			{
				main_region_Counting_S3_A0_react(handle, transitioned);
				break;
			}
			case Statechart_main_region_Counting_S3_A1 :
			{
				main_region_Counting_S3_A1_react(handle, transitioned);
				break;
			}
			default: 
				/* do nothing */
				break;
		}
	} 
}


void statechart_raise_tick(Statechart* handle)
{
	handle->iface.tick_raised = bool_true;
}

void statechart_raise_init(Statechart* handle)
{
	handle->iface.init_raised = bool_true;
}


sc_observable* statechart_get_end(Statechart* handle)
{
	return &handle->iface.end;
}

sc_boolean statechart_get_aout(const Statechart* handle)
{
	return handle->iface.Aout;
}
void statechart_set_aout(Statechart* handle, sc_boolean value)
{
	handle->iface.Aout = value;
}
sc_boolean statechart_get_bout(const Statechart* handle)
{
	return handle->iface.Bout;
}
void statechart_set_bout(Statechart* handle, sc_boolean value)
{
	handle->iface.Bout = value;
}
sc_boolean statechart_get_cout(const Statechart* handle)
{
	return handle->iface.Cout;
}
void statechart_set_cout(Statechart* handle, sc_boolean value)
{
	handle->iface.Cout = value;
}

/* implementations of all internal functions */

/* 'default' enter sequence for state Not Counting */
static void enseq_main_region_Not_Counting_default(Statechart* handle)
{
	/* 'default' enter sequence for state Not Counting */
	handle->stateConfVector[0] = Statechart_main_region_Not_Counting;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Counting */
static void enseq_main_region_Counting_default(Statechart* handle)
{
	/* 'default' enter sequence for state Counting */
	enseq_main_region_Counting_S1_default(handle);
	enseq_main_region_Counting_S2_default(handle);
	enseq_main_region_Counting_S3_default(handle);
}

/* 'default' enter sequence for state C0 */
static void enseq_main_region_Counting_S1_C0_default(Statechart* handle)
{
	/* 'default' enter sequence for state C0 */
	handle->stateConfVector[0] = Statechart_main_region_Counting_S1_C0;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state C1 */
static void enseq_main_region_Counting_S1_C1_default(Statechart* handle)
{
	/* 'default' enter sequence for state C1 */
	handle->stateConfVector[0] = Statechart_main_region_Counting_S1_C1;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state B0 */
static void enseq_main_region_Counting_S2_B0_default(Statechart* handle)
{
	/* 'default' enter sequence for state B0 */
	handle->stateConfVector[1] = Statechart_main_region_Counting_S2_B0;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state B1 */
static void enseq_main_region_Counting_S2_B1_default(Statechart* handle)
{
	/* 'default' enter sequence for state B1 */
	handle->stateConfVector[1] = Statechart_main_region_Counting_S2_B1;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state A0 */
static void enseq_main_region_Counting_S3_A0_default(Statechart* handle)
{
	/* 'default' enter sequence for state A0 */
	handle->stateConfVector[2] = Statechart_main_region_Counting_S3_A0;
	handle->stateConfVectorPosition = 2;
}

/* 'default' enter sequence for state A1 */
static void enseq_main_region_Counting_S3_A1_default(Statechart* handle)
{
	/* 'default' enter sequence for state A1 */
	handle->stateConfVector[2] = Statechart_main_region_Counting_S3_A1;
	handle->stateConfVectorPosition = 2;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region S1 */
static void enseq_main_region_Counting_S1_default(Statechart* handle)
{
	/* 'default' enter sequence for region S1 */
	react_main_region_Counting_S1__entry_Default(handle);
}

/* 'default' enter sequence for region S2 */
static void enseq_main_region_Counting_S2_default(Statechart* handle)
{
	/* 'default' enter sequence for region S2 */
	react_main_region_Counting_S2__entry_Default(handle);
}

/* 'default' enter sequence for region S3 */
static void enseq_main_region_Counting_S3_default(Statechart* handle)
{
	/* 'default' enter sequence for region S3 */
	react_main_region_Counting_S3__entry_Default(handle);
}

/* Default exit sequence for state Not Counting */
static void exseq_main_region_Not_Counting(Statechart* handle)
{
	/* Default exit sequence for state Not Counting */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state Counting */
static void exseq_main_region_Counting(Statechart* handle)
{
	/* Default exit sequence for state Counting */
	exseq_main_region_Counting_S1(handle);
	exseq_main_region_Counting_S2(handle);
	exseq_main_region_Counting_S3(handle);
}

/* Default exit sequence for state C0 */
static void exseq_main_region_Counting_S1_C0(Statechart* handle)
{
	/* Default exit sequence for state C0 */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state C1 */
static void exseq_main_region_Counting_S1_C1(Statechart* handle)
{
	/* Default exit sequence for state C1 */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state B0 */
static void exseq_main_region_Counting_S2_B0(Statechart* handle)
{
	/* Default exit sequence for state B0 */
	handle->stateConfVector[1] = Statechart_last_state;
	handle->stateConfVectorPosition = 1;
}

/* Default exit sequence for state B1 */
static void exseq_main_region_Counting_S2_B1(Statechart* handle)
{
	/* Default exit sequence for state B1 */
	handle->stateConfVector[1] = Statechart_last_state;
	handle->stateConfVectorPosition = 1;
}

/* Default exit sequence for state A0 */
static void exseq_main_region_Counting_S3_A0(Statechart* handle)
{
	/* Default exit sequence for state A0 */
	handle->stateConfVector[2] = Statechart_last_state;
	handle->stateConfVectorPosition = 2;
}

/* Default exit sequence for state A1 */
static void exseq_main_region_Counting_S3_A1(Statechart* handle)
{
	/* Default exit sequence for state A1 */
	handle->stateConfVector[2] = Statechart_last_state;
	handle->stateConfVectorPosition = 2;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Not_Counting :
		{
			exseq_main_region_Not_Counting(handle);
			break;
		}
		case Statechart_main_region_Counting_S1_C0 :
		{
			exseq_main_region_Counting_S1_C0(handle);
			break;
		}
		case Statechart_main_region_Counting_S1_C1 :
		{
			exseq_main_region_Counting_S1_C1(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Handle exit of all possible states (of Statechart.main_region) at position 1... */
	switch(handle->stateConfVector[ 1 ])
	{
		case Statechart_main_region_Counting_S2_B0 :
		{
			exseq_main_region_Counting_S2_B0(handle);
			break;
		}
		case Statechart_main_region_Counting_S2_B1 :
		{
			exseq_main_region_Counting_S2_B1(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Handle exit of all possible states (of Statechart.main_region) at position 2... */
	switch(handle->stateConfVector[ 2 ])
	{
		case Statechart_main_region_Counting_S3_A0 :
		{
			exseq_main_region_Counting_S3_A0(handle);
			break;
		}
		case Statechart_main_region_Counting_S3_A1 :
		{
			exseq_main_region_Counting_S3_A1(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region S1 */
static void exseq_main_region_Counting_S1(Statechart* handle)
{
	/* Default exit sequence for region S1 */
	/* Handle exit of all possible states (of Statechart.main_region.Counting.S1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Counting_S1_C0 :
		{
			exseq_main_region_Counting_S1_C0(handle);
			break;
		}
		case Statechart_main_region_Counting_S1_C1 :
		{
			exseq_main_region_Counting_S1_C1(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region S2 */
static void exseq_main_region_Counting_S2(Statechart* handle)
{
	/* Default exit sequence for region S2 */
	/* Handle exit of all possible states (of Statechart.main_region.Counting.S2) at position 1... */
	switch(handle->stateConfVector[ 1 ])
	{
		case Statechart_main_region_Counting_S2_B0 :
		{
			exseq_main_region_Counting_S2_B0(handle);
			break;
		}
		case Statechart_main_region_Counting_S2_B1 :
		{
			exseq_main_region_Counting_S2_B1(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region S3 */
static void exseq_main_region_Counting_S3(Statechart* handle)
{
	/* Default exit sequence for region S3 */
	/* Handle exit of all possible states (of Statechart.main_region.Counting.S3) at position 2... */
	switch(handle->stateConfVector[ 2 ])
	{
		case Statechart_main_region_Counting_S3_A0 :
		{
			exseq_main_region_Counting_S3_A0(handle);
			break;
		}
		case Statechart_main_region_Counting_S3_A1 :
		{
			exseq_main_region_Counting_S3_A1(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Not_Counting_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Counting_S1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Counting_S1_C0_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Counting_S2__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Counting_S2_B0_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Counting_S3__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Counting_S3_A0_default(handle);
}


static sc_integer react(Statechart* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_Not_Counting_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Not Counting. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.iface.init_raised == bool_true)
		{ 
			exseq_main_region_Not_Counting(handle);
			enseq_main_region_Counting_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Counting. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.internal.local_end_raised == bool_true)
		{ 
			exseq_main_region_Counting(handle);
			enseq_main_region_Not_Counting_default(handle);
			react(handle, 0);
			transitioned_after = 2;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_S1_C0_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state C0. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.internal.lt2_raised == bool_true)
		{ 
			exseq_main_region_Counting_S1_C0(handle);
			enseq_main_region_Counting_S1_C1_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.Cout = bool_false;
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_S1_C1_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state C1. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.internal.lt2_raised == bool_true)
		{ 
			exseq_main_region_Counting_S1_C1(handle);
			sc_observable_next(&handle->iface.end);
			handle->internal.local_end_raised = bool_true;
			enseq_main_region_Counting_S1_C0_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.Cout = bool_true;
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_S2_B0_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state B0. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (1))
	{ 
		if (handle->current.internal.lt1_raised == bool_true)
		{ 
			exseq_main_region_Counting_S2_B0(handle);
			enseq_main_region_Counting_S2_B1_default(handle);
			transitioned_after = 1;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.Bout = bool_false;
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_S2_B1_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state B1. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (1))
	{ 
		if (handle->current.internal.lt1_raised == bool_true)
		{ 
			exseq_main_region_Counting_S2_B1(handle);
			handle->internal.lt2_raised = bool_true;
			enseq_main_region_Counting_S2_B0_default(handle);
			transitioned_after = 1;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.Bout = bool_true;
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_S3_A0_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state A0. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (2))
	{ 
		if (handle->current.iface.tick_raised == bool_true)
		{ 
			exseq_main_region_Counting_S3_A0(handle);
			enseq_main_region_Counting_S3_A1_default(handle);
			main_region_Counting_react(handle, 0);
			transitioned_after = 2;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.Aout = bool_false;
		transitioned_after = main_region_Counting_react(handle, transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Counting_S3_A1_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state A1. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (2))
	{ 
		if (handle->current.iface.tick_raised == bool_true)
		{ 
			exseq_main_region_Counting_S3_A1(handle);
			handle->internal.lt1_raised = bool_true;
			enseq_main_region_Counting_S3_A0_default(handle);
			main_region_Counting_react(handle, 0);
			transitioned_after = 2;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.Aout = bool_true;
		transitioned_after = main_region_Counting_react(handle, transitioned_before);
	} 
	return transitioned_after;
}




